language: java
jdk:
   - oraclejdk8
script: mvn clean install --batch-mode
matrix:
  - jdk: oraclejdk8
branches:
  only:
    - master
after_success:
  - mvn jacoco:report coveralls:report
notifications:
  email: false
sudo: false
